language: node_js
node_js:
  - node
before_script:
  - npm install -g npm@latest
  - npm ci
script:
  - npm test
  - npm run build
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: elshinnaweyom@gmail.com
  api_key:
    secure: Vjom5U9EcrY9FzcLZ821wdT4rJS3iVOBjFLod7xiiyKZO0I43lb+qcKwoFRucRDcBEP0ckts7DyKxnknvsemWd12ePTKlwILfO3i1g65UEAL66DQrZb85BSS9Ib06Naq+D81kv3hFE5nk9+67v33ZZ8KpT7+Ih/GFPqsyqUhE6Ja9hfAd7/1TVTxm64kJAj2h8YxNtYksNe+/uafEoMIngO4Ov3RIDynPTezMHspN4Wz4+22IGvb/d1tR9ElmEyIVP1ezVmkQ9Lai/nGNihh6x+9qOBjNUjn7pQs56keKCyAAgK4dbqdb1aU5XB8fikHOZnwt73vErjJa3nSc16BeUTzToxxpXRsbsK+VM6chrbZxZXAwynD9ut8ChXmeZDJm8sKadsT3CfVd4UPENe6LWSHnLPWM/hzGpCnU7VGg9NijXEjZ2VNVG5dle1VjZM7xjdmRliQ4z3FbeGspAl4gXYKfly6HgACanl2hL0RwjOTL/hLKb+ChCbKzgVga6yITeNB5MY5i587Z7wNphvgt2UR3Rtka71LwOL8VZ3up17OPy8QZNnq9VhCGmVkXQOjQslO0rI+2vij2tfc0nU/2qAT3jlqLiMXgr1tGdPeIfFQEMXeqLVirzbGtB/8F8znWXXKpo1vyElJjAzDkhR/GaiyoAFUO8qHC//9gp9WLak=
