language: node_js
node_js:
- node
before_script:
- npm install -g npm@latest
- npm ci
script:
- npm test
- npm run build
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: elshinnaweyom@gmail.com
  api_key:
    secure: B82Sv/HErUuB+qUJi9/V3Konnd+0InO7pHO6N8TOmq9unDOJyo/6pn67iIwfC6eAZ4LlLv3fOdEwbbdAfWui5coh5zPsM4Ey90Y/U6XUfag62Rbm0xzysvk6UvzRSR3ZR2wz9A1Zii2+55Ssne+POMX7IAscEHzI5UxnWDX3gXbeXHXN1SWKMUw8hxIPFjP4b2SR3VMV5Ync2EWSmOqs4RpwIAqimKP0PWTNGZk+Gxof1F0a3U5bB7sLxYBpVqK1aJ2pSIXvscmvjwpgJAGSsszeSc4oQQyL8jrPl3oUKqK6A/J0xz/B/+LXIS/jDd45sen/Qxpnrmc8xOOi2E+ZFsV+FTGShrFrdkkyuVyj+pIRH3o9qv3dGFdHVsmdcJcN/gIiQmVkx2WuxllpH0CIZG7t66l5cZvSWZr1rDI33mEq8EuR6G+opyic7KEtxTrlKEHwcsG5X3kS98a7CGP1VipIQlyKYnDbUHRHaRiPQsFiw4vrLlxJnMsHhXtTeEG9NC+ZPVmx7UFrkOl2PEmdyLndgZKJ5nGp3hhqaiUiJbKbUPRsWJ7Lr6yoyjhSFWHlv/KtToiEMs+jb2Da12Q2YOhXeAGgY4pdwzk7Zm0ULg/Oc9orbjgw8xJREp0g0eSaZQPXSlbwbhs9rsnWc4GhQsf7sYuLMJEb/G9RJJcs8H0=
